apiVersion: v1
kind: Namespace
metadata:
  name: crud-app-ns
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: crud-app-ns
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: QXAwMHJQYSQkdzByZCE=
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app-db-deployment
  namespace: crud-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-db
  template:
    metadata:
      labels:
        name: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data 
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data-pvc-temp
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: crud-app-ns
spec:
  selector:
    name: postgres-db
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app-backend-deployment
  namespace: crud-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend
  template:
    metadata:
      labels:
        name: backend
    spec:
      containers:
      - name: backend
        image: final_assignment-backend
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: db_address
          value: db-service
        - name: db_name
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_DB
        - name: db_username
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: crud-app-ns
spec:
  selector:
    name: backend
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
---       
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv-temp
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/postgres-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc-temp
  namespace: crud-app-ns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---


