apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: final-assignment-ns
spec:
  selector:
    name: backend
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP