apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app-db-deployment
  namespace: final-assignment-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-db
  template:
    metadata:
      labels:
        name: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc