apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/postgres-data