apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: final-assignment-ns
spec:
  selector:
    name: postgres-db
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP